### ISSUE TITLE
Firebird 4

### ISSUE THREAD

**Issue by Hugolarson** [mariuz/flamerobin#258] opened 2022-05-10 16:28 UTC
Hello,

Flamerobin (flamerobin-0.9.3.e6015349) does not work with Firebird 4 (zip).
Both Firebird and Flamerobin are 32 Bit.

Tried to put fbclient.dll same folder as flamerobin.exe.

![image](https://user-images.githubusercontent.com/8046614/167677394-5f54f5c8-f016-42f7-be3e-5807c6076071.png)

**Comment by Jdochoa** [comment] 2022-05-10 19:31
Hi @Hugolarson ,

You need install, manuali, the client library.
\firebirdfolder\instclient.exe 
Or
\firebirsfolder\wow64\installclient.exe

I working for selection the library per database, but isnot ready.

./jo

**Comment by Hugolarson** [comment] 2022-05-10 21:26
Hi,

I run the command below but it still does not work

instclient i fbclient
FBCLIENT.DLL has been installed to the System directory.

**Comment by luronumen** [comment] 2022-07-01 11:56
Hi @Hugolarson 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano

**Comment by Hugolarson** [comment] 2022-07-03 06:18
Hi,

Now it seems to find fbclient.dll but when I try connecting to either FB4.0 or FB2.5 database files it wont connect.
With engine 2.5 it connects fine but not engine 4.0.
With engine 4.0 I can connect with isql and jdbc but not flamerobin

firebird.conf
AuthServer = Srp256, Srp, Legacy_Auth
UserManager = Srp, Legacy_UserManager
WireCrypt = Disabled

![image](https://user-images.githubusercontent.com/8046614/177027399-812f4148-7362-4305-b2bc-a3b798f25895.png)

**Comment by Hugolarson** [comment] 2022-10-05 14:15
Hello.
We still have problems with Flamerobin on Windows 10 with FB4.
We love this software and have many installations and want migrate from FB2.5 to FB4.0.

Is it possible for you to make a portable version of Flamerobin where one just place fbclient.dll in same folder and it just works.
That would be awesome.
Thank you for the effort.

**Comment by arvanus** [comment] 2022-10-05 15:25
Hello, what kind of problem do you have with fb4?

Also you can use flamerobin as a portable app, just coping it's folder and using some parameters during startup do use a local config(almost sure you'll find something related here) same for embedded

**Comment by Jdochoa** [comment] 2022-10-05 15:41
Hi @Hugolarson 
Please review this 
https://github.com/mariuz/flamerobin/pull/261

./jo

**Comment by Hugolarson** [comment] 2022-10-05 17:07
Hi,
Tried to put the path to fbclient.dll, which I have placed in flamerobin folder.
I have deleted all old fbclient 2.5.
Same problem with several other Windows 10 computers
It would be great if flamerobin primarily search for fbclient.dll in same folder. 

![image](https://user-images.githubusercontent.com/8046614/194119757-a1f6068a-18be-4282-b370-0468af0d3a8a.png)

**Comment by arvanus** [comment] 2022-10-05 17:38
Hi, are you sure you are using 32bits dll?

**Comment by Hugolarson** [comment] 2022-10-05 17:55
Yes
![image](https://user-images.githubusercontent.com/8046614/194128737-4b35b517-1ae9-4621-aee9-4795b56b81e7.png)

**Comment by Jdochoa** [comment] 2022-10-05 18:20
@Hugolarson 
Could you try to assign the library, in the general configuration?

./jo

**Comment by Jdochoa** [comment] 2022-10-05 18:20
@Hugolarson 
Could you try to assign the library, in the general configuration?

./jo

**Comment by Jdochoa** [comment] 2022-10-05 18:47
> I did already
> 
> ![image](https://user-images.githubusercontent.com/8046614/194133996-22beb40e-36bc-47d1-a801-5de91ca98e6f.png)
> 

There seems to be something wrong with the library you are using.  
Try assigning the library to the FB installation directory

**Comment by Hugolarson** [comment] 2022-10-05 18:57
Don't think so. I tried with IBExpert and it works.
Here is it. 
[fbclient.zip](https://github.com/mariuz/flamerobin/files/9718249/fbclient.zip)

**Comment by Jdochoa** [comment] 2022-10-15 00:00
> Don't think so. I tried with IBExpert and it works. Tried to assign it to FB4 install folder. Same. Here is it. [fbclient.zip](https://github.com/mariuz/flamerobin/files/9718249/fbclient.zip)

Hi @Hugolarson 
Please try this version, information about the latest error is included

[flamerobin.zip](https://github.com/mariuz/flamerobin/files/9790763/flamerobin.zip)

./jo

**Closed** 2023-10-16 15:03 UTC
