### ISSUE TITLE
Grid decimal seperator

### ISSUE THREAD

**Issue by Zeki-Gursoy** [mariuz/flamerobin#190] opened 2021-05-01 11:27 UTC
Grid decimal seperator is "." dot. Can it take from system setting for other cultures ?

**Comment by nLeonardt95** [comment] 2021-05-03 15:35
I would like that very much, too.

**Comment by arvanus** [comment] 2021-05-19 13:11
@Jdochoa this is a nice feature, but breaks compatibility with "COPY AS INSERT/UPDATE"
I'll suggest to rollback for now because this breaks current behavior with the iteration with Firebird itself when I change a value directly from the grid (update)
![image](https://user-images.githubusercontent.com/8182958/118818301-8e759400-b88a-11eb-88ec-956e8b63cd1d.png)

**Comment by Jdochoa** [comment] 2021-05-20 15:49
> 
> 
> @Jdochoa I'll comment this line:
> 
> https://github.com/mariuz/flamerobin/blob/f909af0786116f5d871c1c6138b4226b71affbc6/src/main.cpp#L84
> 
> and generate a new snapshot, ok?

OK

./jo

**Comment by arvanus** [comment] 2021-06-06 21:53
@Jdochoa I downloaded and tried this option, but looks like location is always enabled checking or not the checkbox at `Preferences` my grid has ',' (comma) instead of '.' (dot) 
By the way my locale is indeed ',' (comma) but I prefer using dot 😸

**Comment by Jdochoa** [comment] 2021-06-07 01:12
> 
> 
> @Jdochoa I downloaded and tried this option, but looks like location is always enabled checking or not the checkbox at `Preferences` my grid has ',' (comma) instead of '.' (dot)
> By the way my locale is indeed ',' (comma) but I prefer using dot 😸

![imagen](https://user-images.githubusercontent.com/11672188/120946833-0e10b900-c6fb-11eb-8b4f-84d8f83e0a33.png)

**Comment by Jdochoa** [comment] 2021-06-07 02:23
> 
> 
> @Jdochoa I downloaded and tried this option, but looks like location is always enabled checking or not the checkbox at `Preferences` my grid has ',' (comma) instead of '.' (dot)
> By the way my locale is indeed ',' (comma) but I prefer using dot 😸

Hi @arvanus 
I can't reproduce it.
you have more information?

The next snapshot depend of this.

Thank you.

./jo

**Comment by arvanus** [comment] 2021-06-07 02:30
Hello @Jdochoa!
So, I unchecked this option and the grid keep using comma, just after I closed and reopened completely Fr that if worked OK
I think that just putting a label informing the need to restart is enough!
Something like this:
![image](https://user-images.githubusercontent.com/8182958/120951365-09f69280-c71f-11eb-93e1-e3252fff541e.png)

**Comment by arvanus** [comment] 2021-06-07 02:44
I found the "problem"
https://github.com/mariuz/flamerobin/blob/4f17dc5b88e09fc7bc460ae1647af153b37e2eb8/src/config/Config.cpp#L409
default should be "false"
I'll change it right here and commit
For now, it's good enough to the snapshot!

**Comment by arvanus** [comment] 2021-06-07 02:46
Or... change here to true:
https://github.com/mariuz/flamerobin/blob/4f17dc5b88e09fc7bc460ae1647af153b37e2eb8/conf-defs/fr_settings.confdef#L15
You decide @Jdochoa :)

**Comment by Jdochoa** [comment] 2021-06-07 03:07
@arvanus  i committed two changes:
- Change default to "False"
- Reload configuration to save changes to settings.

With this, please generate a new snapshot.
./jo

**Comment by arvanus** [comment] 2021-06-07 03:08
Nice! 
please pull request :)

**Comment by arvanus** [comment] 2021-06-07 03:12
Perfect! :D
I'll edit What's New in the docs and generate a snapshot

**Comment by arvanus** [comment] 2021-06-07 03:36
New snapshot available! 
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8

@Zeki-Gursoy can you try this snapshot and close this issue?
@Jdochoa you are awesome :) 
Thanks!

**Comment by Zeki-Gursoy** [comment] 2021-06-07 22:17
Perfect for pasting into Excel and exporting to CSV.
@Jdochoa, Thank you very much ;)

**Comment by arvanus** [comment] 2021-06-22 21:40
@Jdochoa 
when I try to update a integer value, I'm getting this error here:
![image](https://user-images.githubusercontent.com/8182958/123002763-a4dea600-d388-11eb-8d7b-e7d666471f02.png)
Here:
https://github.com/mariuz/flamerobin/blob/d4a6eae13a7b04803cb08c3acb1789c55cd0de8f/src/gui/controls/DataGridRows.cpp#L558-L559

Debugging, the string comes as "1.0000" instead of simply '1'
This error occurs since snapshot 8

**Closed** 2021-06-22 21:51 UTC
